const fs = require('fs');
const path = require('path');

// Paths
const articlesDir = path.join(__dirname, '../src/articles');
const outputFile = path.join(__dirname, '../src/utils/markdownContent.js');

// Function to read all markdown files and generate content
function generateMarkdownContent() {
    const markdownContent = {};
    
    // Read all files in the articles directory
    const files = fs.readdirSync(articlesDir);
    
    files.forEach(file => {
        if (file.endsWith('.md') && file !== 'README.md') {
            const filePath = path.join(articlesDir, file);
            const content = fs.readFileSync(filePath, 'utf8');
            
            // Convert filename to article ID (remove .md extension)
            const articleId = file.replace('.md', '').replace('_', '-');
            
            // Store content as-is without escaping - JSON.stringify will handle it properly
            markdownContent[articleId] = content;
        }
    });
    
    // Generate JavaScript file content
    const jsContent = `// Auto-generated file containing markdown content
// This file is generated by scripts/generateMarkdownContent.js
// Do not edit manually - run 'npm run generate-markdown' to update

/* eslint-disable no-template-curly-in-string */
export const markdownContent = ${JSON.stringify(markdownContent, null, 2)};

/**
 * Gets the markdown content for an article by ID
 * @param {string} articleId - The ID of the article
 * @returns {string} - The markdown content as a string
 */
export const getMarkdownContent = (articleId) => {
    return markdownContent[articleId] || '';
};

/**
 * Gets all available article IDs
 * @returns {string[]} - Array of available article IDs
 */
export const getAvailableArticleIds = () => {
    return Object.keys(markdownContent);
};

/**
 * Checks if an article ID has content
 * @param {string} articleId - The ID to check
 * @returns {boolean} - True if the article has content
 */
export const hasMarkdownContent = (articleId) => {
    return articleId in markdownContent;
};
`;
    
    // Write the generated content to file
    fs.writeFileSync(outputFile, jsContent);
    
    console.log(`✅ Generated markdown content for ${Object.keys(markdownContent).length} articles:`);
    Object.keys(markdownContent).forEach(id => {
        console.log(`   - ${id}`);
    });
    console.log(`📄 Output file: ${outputFile}`);
}

// Run the generator
generateMarkdownContent(); 